apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-request-deployment
  labels:
    app: kube-request
spec:
  selector:
    matchLabels:
      app: kube-request
  replicas: 3
  template:
    metadata:
      labels:
        app: kube-request
    spec:
      containers:
      - name: kube-request-container
        image: krq-img:0001
        ports:
        - containerPort: 80
        env:
        - name: podIP
          valueFrom:
            fieldRef:
                fieldPath: status.podIP